## cartridge.properties for cartridge app_custom_menu_categories
#Mon undefined 13 13:13:13 CEST 2025
demandware.cartridges.app_custom_menu_categories.multipleLanguageStorefront=true
demandware.cartridges.app_custom_menu_categories.id=app_custom_menu_categories